### ISSUE TITLE
[Helm] Add more informations about side-instances

### ISSUE THREAD

**Issue by Heiss** [Sciebo-RDS/Sciebo-RDS#186]
RDS can connect to multiple EFSS instances at once. So they want to have side-specific informations like:
- VUE_APP_RDS_EMAIL
- user manual link
- corporate design

This should be handled through the global.domains list in values.yaml, so e.g.

```yaml
global:
  domains:
    - name: owncloud.local # name needs to be exact the same as the second part after last @ in the cloudId
      ADDRESS: https://owncloud.local/owncloud
      OAUTH_CLIENT_ID: ABC
      OAUTH_CLIENT_SECRET: XYZ
      VUE_APP_RDS_EMAIL: mail@side.com
      CORPORATE_DESIGN_CSS: ".design{color:black}"
      VUE_APP_MANUAL_LINK: usermanual.side.com
```

So all sides have different email, small design changes and a manual link.

This needs a rewrite of how the frontend handles such informations given by the backend.
